on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    env:
      ENV: 'staging'
      DEPLOY: 'false'
      RELEASE: 'false'
      MULTIPLICITY: ''


    name: A job to say hello
    steps:
    - name: test
      if: ${ENV} == 'staging'
      run: |
        echo $DEPLOY
        echo $ENV
        echo $RELEASE